[package]
name = "float-ord"
version = "0.1.2"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "A total ordering for floating-point numbers"
license = "MIT / Apache-2.0"
repository = "https://github.com/notriddle/rust-float-ord"
documentation = "https://docs.rs/float-ord/0.1.2/float-ord/"

[dependencies]
pdqsort = { version = "1.0.0", optional = true }

[dev-dependencies]
rand = "0.3"

[badges]
travis-ci = { repository = "notriddle/rust-float-ord" }
